config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#home'
  get '/' => 'pages#home'
  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact-us'
  get 'team' => 'pages#team'
  get 'testimonials' => 'pages#testimonials'
  get 'services' => 'pages#services'
  get 'portfolio' => 'pages#portfolio'
  get 'pricing' => 'pages#pricing'
  get 'blog' => 'pages#blog'
  get 'terms' => 'pages#terms'
  get 'privacy' => 'pages#privacy'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Test</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
      <!-- Include the Boxicons CSS file from a CDN --><!-- Include the Boxicons CSS file from a different CDN -->
     <link rel="stylesheet" href="https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css">
     

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag 'main' %>

  </head>

  <body>
     <!-- ======= Header ======= -->
  <header id="header" class="fixed-top d-flex align-items-center">
    <div class="container d-flex align-items-center">

<h1 class="logo me-auto"><%= link_to "Hair Styles", root_path %></h1>
   <nav id="navbar" class="navbar navbar-toggleable-md">
        <ul>
          <li><%= link_to "Home", root_path, class: "active" %></li>
          <li class="dropdown">
            <%= link_to "about" do %>
              <span>About</span> <i class="bi bi-chevron-down"></i>
            <% end %>
            <ul>
              <li><%= link_to "About", about_path %></li>
              <li><%= link_to "Team", team_path %></li>
              <li><%= link_to "Testimonials", testimonials_path %></li>
            </ul>
          </li>
          <li><%= link_to "Services", services_path %></li>
          <li><%= link_to "Portfolio", portfolio_path %></li>
          <li><%= link_to "Pricing", pricing_path %></li>
          <li><%= link_to "Blog", blog_path %></li>
          <li><%= link_to "Contact", contact_path %></li>
          <li><%= link_to "Get Started", root_path, class: "getstarted" %></li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->
<!-- Flash Message -->

<% flash.each do |name,message| %>
<% content_tag(:div, message, class:"alert alert-info  #{name}") %>
<% end -%>
    <%= yield %>
    <footer id="footer">
    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6">
            <div class="footer-info">
              <h3>Hair Styles</h3>
              <p>
               Fortune Logix Inc,<br>
               7-1-55-6 Suite: 201a,<br>
               Sri Saikasi Mansions,<br>
               Kirlampudi Layout,<br>
               Vishakapatnam, 530003,<br>
               Andhra Pradesh, India <br>
               <br><br>
               <strong>Email:</strong>hello@fortunelogics.com<br>
              </p>
              <div class="social-links mt-3">
                <a href="" class="twitter"><i class="bx bxl-twitter"></i></a>
                <a href="" class="facebook"><i class="bx bxl-facebook"></i></a>
                <a href="" class="instagram"><i class="bx bxl-instagram"></i></a>
                <a href="" class="google-plus"><i class="bx bxl-skype"></i></a>
              </div>
            </div>
          </div>

          <div class="col-lg-2 col-md-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i><%= link_to "Home", root_path %></li>
              <li><i class="bx bx-chevron-right"></i><%= link_to "About Us", about_path %></li>
              <li><i class="bx bx-chevron-right"></i><%= link_to "Services", services_path %></li>
              <li><i class="bx bx-chevron-right"></i><%= link_to "Terms of service", terms_path %></li>
              <li><i class="bx bx-chevron-right"></i> <%= link_to "Privacy policy", privacy_path %></li>
            </ul>
          </div>
          </div>

        </div>
      </div>
    </div>

    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong><span>Hair Styles</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/sailor-free-bootstrap-theme/ -->
        Designed by <a href="https://fortunelogics.com/">Fortune Logix Inc</a>
      </div>
    </div>
  </footer>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>We're working on our One Month Rails Project.</p>

app/views/pages/contact-us.html.erb
<h1>Contact Us</h1>
<p>Thank you for your interest in contacting us. Please fill out the form below and we will get back to you as soon as possible.</p>